name: bharatx_flutter_startup
description: Flutter wrapper for Startup Tier from BharatX SDK
version: 1.0.3-alpha2
homepage: https://bharatx.tech/
repository: https://github.com/bharatx-in/bharatx_flutter_startup

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  bharatx_flutter_securityhelpers: ^1.0.2-alpha2
  bharatx_flutter_common: ^1.0.3-alpha2
  bharatx_flutter_alternatedata: ^1.0.2-alpha1

flutter:
  plugin:
    platforms:
      android:
        package: tech.bharatx.bharatx_flutter_startup
        pluginClass: BharatxFlutterStartupPlugin
